version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  seed:
    image: node:18
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - db
    command: /bin/sh -c "npm install && npm run build && npm run seed"
